// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-practice/apps/hello/access"
	"gin-practice/libs/router"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApplication() (application, error) {
	helloApp := access.NewHelloApp()
	mainApplication := application{
		helloApp: helloApp,
	}
	return mainApplication, nil
}

// wire.go:

type application struct {
	helloApp *access.HelloApp
}

func (app *application) Register(engine *gin.Engine) error {
	router.RegisterSchema("rest", app.helloApp)
	return router.RegisterUrlPatterns(engine)
}

func InitApp(engine *gin.Engine) error {
	app, err := InitializeApplication()
	if err != nil {
		return err
	}
	return app.Register(engine)
}
